---
info:
  title: Braveblock
  description: A fast and easy adblockplus parser and matcher based on adblock-rust
    package
  x-cortex-git:
    github:
      alias: intsightsorg
      repository: Intsights/braveblock
  x-cortex-tag: braveblock
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: threatintel-brand-security
  x-cortex-groups:
  - exposure:internal-ship
  - target:library
openapi: 3.0.1
servers:
- url: "/"
